# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Arty-A7-35-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mig_7series_0_2/design_1_mig_7series_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mig_7series_0_2 || ORIG_REF_NAME==design_1_mig_7series_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reset_inv_0_0/design_1_reset_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reset_inv_0_0 || ORIG_REF_NAME==design_1_reset_inv_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_1/design_1_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_1 || ORIG_REF_NAME==design_1_microblaze_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_v10_2/design_1_dlmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_2 || ORIG_REF_NAME==design_1_dlmb_v10_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_v10_2/design_1_ilmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_2 || ORIG_REF_NAME==design_1_ilmb_v10_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_bram_if_cntlr_2/design_1_dlmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_bram_if_cntlr_2/design_1_ilmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==design_1_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_lmb_bram_2/design_1_lmb_bram_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_lmb_bram_2 || ORIG_REF_NAME==design_1_lmb_bram_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mdm_1_2/design_1_mdm_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mdm_1_2 || ORIG_REF_NAME==design_1_mdm_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_mig_7series_0_83M_2/design_1_rst_mig_7series_0_83M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_mig_7series_0_83M_2 || ORIG_REF_NAME==design_1_rst_mig_7series_0_83M_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_uartlite_0_2/design_1_axi_uartlite_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_2 || ORIG_REF_NAME==design_1_axi_uartlite_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_quad_spi_0_1/design_1_axi_quad_spi_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_quad_spi_0_1 || ORIG_REF_NAME==design_1_axi_quad_spi_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_2/design_1_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_2 || ORIG_REF_NAME==design_1_xbar_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_axi_periph_4/design_1_microblaze_0_axi_periph_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_periph_4 || ORIG_REF_NAME==design_1_microblaze_0_axi_periph_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_1/design_1_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_1 || ORIG_REF_NAME==design_1_axi_smc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_PmodSD_0_0/design_1_PmodSD_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_PmodSD_0_0 || ORIG_REF_NAME==design_1_PmodSD_0_0} -quiet] -quiet

# XDC: c:/Users/rikir/Documents/FPGA_projects/Vitis_project_on_SPI_flash/Vitis_project_on_SPI_flash.gen/sources_1/bd/design_1/design_1_ooc.xdc
